apiVersion: v1
kind: Service
metadata:
  name: {{ include "smarthome.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "smarthome.name" . }}
  ports:
  - port: {{ .Values.voiceService.service.port }}
    targetPort: {{ .Values.voiceService.service.targetPort }}
    name: voice
  - port: {{ .Values.videoService.service.port }}
    targetPort: {{ .Values.videoService.service.targetPort }}
    name: video
  - port: {{ .Values.notificationService.service.port }}
    targetPort: {{ .Values.notificationService.service.targetPort }}
    name: notification
  - port: {{ .Values.natsStreaming.service.port }}
    targetPort: {{ .Values.natsStreaming.service.targetPort }}
    name: nats-streaming